name: "Build Windows Executable"

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install pip
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install sslyze dependencies
      run: python -m pip install -e .

    - name: Install dev dependencies including cx_freeze
      run: python -m pip install -r requirements-dev.txt

    - name: Build Windows executable
      run: python setup.py build_exe

    - uses: actions/upload-artifact@v2
      with:
        path: ./build/*
