name: Run tests with lowest supported version of pydantic

on:
  push:
    branches: [release]
  pull_request:
    branches: [ release, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install sslyze dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -e .

      - name: Install pydantic 2.2
        run: python -m pip install "pydantic==2.2"

      - name: Install dev dependencies
        run: python -m pip install -r requirements-dev.txt

      - name: Run tests
        run: python -m invoke test
