# TODO(#617): Delete this file
name: Run tests with pydantic 1.10

on:
  push:
    branches: [release]
  pull_request:
    branches: [ release, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install sslyze dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -e .

      - name: Install pydantic 1.10
        run: python -m pip install "pydantic<2"

      - name: Install dev dependencies
        run: python -m pip install -r requirements-dev.txt

      - name: Run tests
        run: python -m invoke test
