name: Test Module Setup

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install pip
      run: |
        python -m pip install --upgrade pip setuptools

    - name: Test SSLyze module setup
      run: |
        python setup.py install
        cd docs  # Switch folder to avoid conflicts between ./sslyze and the installed sslyze module
        python ../api_sample.py
